# line length allowd
line_length: 250

# type name length
identifier_name:
  min_length: 2
  
# disabled rules
disabled_rules:
  - redundant_string_enum_value
  - redundant_void_return
  - switch_case_alignment
  - empty_enum_arguments
  - cyclomatic_complexity
  - trailing_whitespace
  - redundant_sendable
